import type { Metadata } from "next";
import "./globals.css";

import { lineSeedSansTH } from "./font";
import Footer from "@/components/ui/Footer";
import WatchCursor from "@/components/ui/WatchCursor";
import Header from "@/components/layout/Header";
import CookieConsent from "@/components/cookie/CookieConsent";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className={lineSeedSansTH.className}>
        <Header />
        <WatchCursor />
        <main>{children}</main>
        <CookieConsent />
        <Footer />
      </body>
    </html>
  );
}
