import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { lineSeedSansTH } from "./font";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className={lineSeedSansTH.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
